# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: write

# Controls when the workflow will run
on: 
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: sergeysova/jq-action@v2
        with:
          cmd: |
            make build RELEASE_VERSION=${RELEASE_VERSION}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          zip -r covalon-deities.zip packs/ module.json README.md
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "module.json,covalon-deities.zip"
